export type CountryDialEntry = { iso2: string; name: string; dial: string };

/**
 * Calling codes derived from mledoze/countries (idd root + suffixes).
 * Multiple rows per ISO when the dataset lists NANP-style area codes separately.
 */
export const COUNTRY_DIAL_ENTRIES: CountryDialEntry[] = [
  { iso2: "AF", name: "Afghanistan", dial: "+93" },
  { iso2: "AX", name: "Åland Islands", dial: "+35818" },
  { iso2: "AL", name: "Albania", dial: "+355" },
  { iso2: "DZ", name: "Algeria", dial: "+213" },
  { iso2: "AS", name: "American Samoa", dial: "+1684" },
  { iso2: "AD", name: "Andorra", dial: "+376" },
  { iso2: "AO", name: "Angola", dial: "+244" },
  { iso2: "AI", name: "Anguilla", dial: "+1264" },
  { iso2: "AG", name: "Antigua and Barbuda", dial: "+1268" },
  { iso2: "AR", name: "Argentina", dial: "+54" },
  { iso2: "AM", name: "Armenia", dial: "+374" },
  { iso2: "AW", name: "Aruba", dial: "+297" },
  { iso2: "AU", name: "Australia", dial: "+61" },
  { iso2: "AT", name: "Austria", dial: "+43" },
  { iso2: "AZ", name: "Azerbaijan", dial: "+994" },
  { iso2: "BS", name: "Bahamas", dial: "+1242" },
  { iso2: "BH", name: "Bahrain", dial: "+973" },
  { iso2: "BD", name: "Bangladesh", dial: "+880" },
  { iso2: "BB", name: "Barbados", dial: "+1246" },
  { iso2: "BY", name: "Belarus", dial: "+375" },
  { iso2: "BE", name: "Belgium", dial: "+32" },
  { iso2: "BZ", name: "Belize", dial: "+501" },
  { iso2: "BJ", name: "Benin", dial: "+229" },
  { iso2: "BM", name: "Bermuda", dial: "+1441" },
  { iso2: "BT", name: "Bhutan", dial: "+975" },
  { iso2: "BO", name: "Bolivia", dial: "+591" },
  { iso2: "BA", name: "Bosnia and Herzegovina", dial: "+387" },
  { iso2: "BW", name: "Botswana", dial: "+267" },
  { iso2: "BV", name: "Bouvet Island", dial: "+47" },
  { iso2: "BR", name: "Brazil", dial: "+55" },
  { iso2: "IO", name: "British Indian Ocean Territory", dial: "+246" },
  { iso2: "VG", name: "British Virgin Islands", dial: "+1284" },
  { iso2: "BN", name: "Brunei", dial: "+673" },
  { iso2: "BG", name: "Bulgaria", dial: "+359" },
  { iso2: "BF", name: "Burkina Faso", dial: "+226" },
  { iso2: "BI", name: "Burundi", dial: "+257" },
  { iso2: "KH", name: "Cambodia", dial: "+855" },
  { iso2: "CM", name: "Cameroon", dial: "+237" },
  { iso2: "CA", name: "Canada", dial: "+1204" },
  { iso2: "CA", name: "Canada", dial: "+1226" },
  { iso2: "CA", name: "Canada", dial: "+1236" },
  { iso2: "CA", name: "Canada", dial: "+1249" },
  { iso2: "CA", name: "Canada", dial: "+1250" },
  { iso2: "CA", name: "Canada", dial: "+1263" },
  { iso2: "CA", name: "Canada", dial: "+1289" },
  { iso2: "CA", name: "Canada", dial: "+1306" },
  { iso2: "CA", name: "Canada", dial: "+1343" },
  { iso2: "CA", name: "Canada", dial: "+1354" },
  { iso2: "CA", name: "Canada", dial: "+1365" },
  { iso2: "CA", name: "Canada", dial: "+1367" },
  { iso2: "CA", name: "Canada", dial: "+1368" },
  { iso2: "CA", name: "Canada", dial: "+1382" },
  { iso2: "CA", name: "Canada", dial: "+1387" },
  { iso2: "CA", name: "Canada", dial: "+1403" },
  { iso2: "CA", name: "Canada", dial: "+1416" },
  { iso2: "CA", name: "Canada", dial: "+1418" },
  { iso2: "CA", name: "Canada", dial: "+1428" },
  { iso2: "CA", name: "Canada", dial: "+1431" },
  { iso2: "CA", name: "Canada", dial: "+1437" },
  { iso2: "CA", name: "Canada", dial: "+1438" },
  { iso2: "CA", name: "Canada", dial: "+1450" },
  { iso2: "CA", name: "Canada", dial: "+1468" },
  { iso2: "CA", name: "Canada", dial: "+1474" },
  { iso2: "CA", name: "Canada", dial: "+1506" },
  { iso2: "CA", name: "Canada", dial: "+1514" },
  { iso2: "CA", name: "Canada", dial: "+1519" },
  { iso2: "CA", name: "Canada", dial: "+1548" },
  { iso2: "CA", name: "Canada", dial: "+1579" },
  { iso2: "CA", name: "Canada", dial: "+1581" },
  { iso2: "CA", name: "Canada", dial: "+1584" },
  { iso2: "CA", name: "Canada", dial: "+1587" },
  { iso2: "CA", name: "Canada", dial: "+1600" },
  { iso2: "CA", name: "Canada", dial: "+1604" },
  { iso2: "CA", name: "Canada", dial: "+1613" },
  { iso2: "CA", name: "Canada", dial: "+1622" },
  { iso2: "CA", name: "Canada", dial: "+1633" },
  { iso2: "CA", name: "Canada", dial: "+1639" },
  { iso2: "CA", name: "Canada", dial: "+1644" },
  { iso2: "CA", name: "Canada", dial: "+1647" },
  { iso2: "CA", name: "Canada", dial: "+1655" },
  { iso2: "CA", name: "Canada", dial: "+1672" },
  { iso2: "CA", name: "Canada", dial: "+1677" },
  { iso2: "CA", name: "Canada", dial: "+1683" },
  { iso2: "CA", name: "Canada", dial: "+1688" },
  { iso2: "CA", name: "Canada", dial: "+1705" },
  { iso2: "CA", name: "Canada", dial: "+1709" },
  { iso2: "CA", name: "Canada", dial: "+1742" },
  { iso2: "CA", name: "Canada", dial: "+1753" },
  { iso2: "CA", name: "Canada", dial: "+1778" },
  { iso2: "CA", name: "Canada", dial: "+1780" },
  { iso2: "CA", name: "Canada", dial: "+1782" },
  { iso2: "CA", name: "Canada", dial: "+1807" },
  { iso2: "CA", name: "Canada", dial: "+1819" },
  { iso2: "CA", name: "Canada", dial: "+1825" },
  { iso2: "CA", name: "Canada", dial: "+1867" },
  { iso2: "CA", name: "Canada", dial: "+1873" },
  { iso2: "CA", name: "Canada", dial: "+1879" },
  { iso2: "CA", name: "Canada", dial: "+1902" },
  { iso2: "CA", name: "Canada", dial: "+1905" },
  { iso2: "CA", name: "Canada", dial: "+1942" },
  { iso2: "CV", name: "Cape Verde", dial: "+238" },
  { iso2: "BQ", name: "Caribbean Netherlands", dial: "+599" },
  { iso2: "KY", name: "Cayman Islands", dial: "+1345" },
  { iso2: "CF", name: "Central African Republic", dial: "+236" },
  { iso2: "TD", name: "Chad", dial: "+235" },
  { iso2: "CL", name: "Chile", dial: "+56" },
  { iso2: "CN", name: "China", dial: "+86" },
  { iso2: "CX", name: "Christmas Island", dial: "+61" },
  { iso2: "CC", name: "Cocos (Keeling) Islands", dial: "+61" },
  { iso2: "CO", name: "Colombia", dial: "+57" },
  { iso2: "KM", name: "Comoros", dial: "+269" },
  { iso2: "CG", name: "Congo", dial: "+242" },
  { iso2: "CK", name: "Cook Islands", dial: "+682" },
  { iso2: "CR", name: "Costa Rica", dial: "+506" },
  { iso2: "HR", name: "Croatia", dial: "+385" },
  { iso2: "CU", name: "Cuba", dial: "+53" },
  { iso2: "CW", name: "Curaçao", dial: "+599" },
  { iso2: "CY", name: "Cyprus", dial: "+357" },
  { iso2: "CZ", name: "Czechia", dial: "+420" },
  { iso2: "DK", name: "Denmark", dial: "+45" },
  { iso2: "DJ", name: "Djibouti", dial: "+253" },
  { iso2: "DM", name: "Dominica", dial: "+1767" },
  { iso2: "DO", name: "Dominican Republic", dial: "+1809" },
  { iso2: "DO", name: "Dominican Republic", dial: "+1829" },
  { iso2: "DO", name: "Dominican Republic", dial: "+1849" },
  { iso2: "CD", name: "DR Congo", dial: "+243" },
  { iso2: "EC", name: "Ecuador", dial: "+593" },
  { iso2: "EG", name: "Egypt", dial: "+20" },
  { iso2: "SV", name: "El Salvador", dial: "+503" },
  { iso2: "GQ", name: "Equatorial Guinea", dial: "+240" },
  { iso2: "ER", name: "Eritrea", dial: "+291" },
  { iso2: "EE", name: "Estonia", dial: "+372" },
  { iso2: "SZ", name: "Eswatini", dial: "+268" },
  { iso2: "ET", name: "Ethiopia", dial: "+251" },
  { iso2: "FK", name: "Falkland Islands", dial: "+500" },
  { iso2: "FO", name: "Faroe Islands", dial: "+298" },
  { iso2: "FJ", name: "Fiji", dial: "+679" },
  { iso2: "FI", name: "Finland", dial: "+358" },
  { iso2: "FR", name: "France", dial: "+33" },
  { iso2: "GF", name: "French Guiana", dial: "+594" },
  { iso2: "PF", name: "French Polynesia", dial: "+689" },
  { iso2: "TF", name: "French Southern and Antarctic Lands", dial: "+262" },
  { iso2: "GA", name: "Gabon", dial: "+241" },
  { iso2: "GM", name: "Gambia", dial: "+220" },
  { iso2: "GE", name: "Georgia", dial: "+995" },
  { iso2: "DE", name: "Germany", dial: "+49" },
  { iso2: "GH", name: "Ghana", dial: "+233" },
  { iso2: "GI", name: "Gibraltar", dial: "+350" },
  { iso2: "GR", name: "Greece", dial: "+30" },
  { iso2: "GL", name: "Greenland", dial: "+299" },
  { iso2: "GD", name: "Grenada", dial: "+1473" },
  { iso2: "GP", name: "Guadeloupe", dial: "+590" },
  { iso2: "GU", name: "Guam", dial: "+1671" },
  { iso2: "GT", name: "Guatemala", dial: "+502" },
  { iso2: "GG", name: "Guernsey", dial: "+44" },
  { iso2: "GN", name: "Guinea", dial: "+224" },
  { iso2: "GW", name: "Guinea-Bissau", dial: "+245" },
  { iso2: "GY", name: "Guyana", dial: "+592" },
  { iso2: "HT", name: "Haiti", dial: "+509" },
  { iso2: "HN", name: "Honduras", dial: "+504" },
  { iso2: "HK", name: "Hong Kong", dial: "+852" },
  { iso2: "HU", name: "Hungary", dial: "+36" },
  { iso2: "IS", name: "Iceland", dial: "+354" },
  { iso2: "IN", name: "India", dial: "+91" },
  { iso2: "ID", name: "Indonesia", dial: "+62" },
  { iso2: "IR", name: "Iran", dial: "+98" },
  { iso2: "IQ", name: "Iraq", dial: "+964" },
  { iso2: "IE", name: "Ireland", dial: "+353" },
  { iso2: "IM", name: "Isle of Man", dial: "+44" },
  { iso2: "IL", name: "Israel", dial: "+972" },
  { iso2: "IT", name: "Italy", dial: "+39" },
  { iso2: "CI", name: "Ivory Coast", dial: "+225" },
  { iso2: "JM", name: "Jamaica", dial: "+1876" },
  { iso2: "JP", name: "Japan", dial: "+81" },
  { iso2: "JE", name: "Jersey", dial: "+44" },
  { iso2: "JO", name: "Jordan", dial: "+962" },
  { iso2: "KZ", name: "Kazakhstan", dial: "+76" },
  { iso2: "KZ", name: "Kazakhstan", dial: "+77" },
  { iso2: "KE", name: "Kenya", dial: "+254" },
  { iso2: "KI", name: "Kiribati", dial: "+686" },
  { iso2: "XK", name: "Kosovo", dial: "+383" },
  { iso2: "KW", name: "Kuwait", dial: "+965" },
  { iso2: "KG", name: "Kyrgyzstan", dial: "+996" },
  { iso2: "LA", name: "Laos", dial: "+856" },
  { iso2: "LV", name: "Latvia", dial: "+371" },
  { iso2: "LB", name: "Lebanon", dial: "+961" },
  { iso2: "LS", name: "Lesotho", dial: "+266" },
  { iso2: "LR", name: "Liberia", dial: "+231" },
  { iso2: "LY", name: "Libya", dial: "+218" },
  { iso2: "LI", name: "Liechtenstein", dial: "+423" },
  { iso2: "LT", name: "Lithuania", dial: "+370" },
  { iso2: "LU", name: "Luxembourg", dial: "+352" },
  { iso2: "MO", name: "Macau", dial: "+853" },
  { iso2: "MG", name: "Madagascar", dial: "+261" },
  { iso2: "MW", name: "Malawi", dial: "+265" },
  { iso2: "MY", name: "Malaysia", dial: "+60" },
  { iso2: "MV", name: "Maldives", dial: "+960" },
  { iso2: "ML", name: "Mali", dial: "+223" },
  { iso2: "MT", name: "Malta", dial: "+356" },
  { iso2: "MH", name: "Marshall Islands", dial: "+692" },
  { iso2: "MQ", name: "Martinique", dial: "+596" },
  { iso2: "MR", name: "Mauritania", dial: "+222" },
  { iso2: "MU", name: "Mauritius", dial: "+230" },
  { iso2: "YT", name: "Mayotte", dial: "+262" },
  { iso2: "MX", name: "Mexico", dial: "+52" },
  { iso2: "FM", name: "Micronesia", dial: "+691" },
  { iso2: "MD", name: "Moldova", dial: "+373" },
  { iso2: "MC", name: "Monaco", dial: "+377" },
  { iso2: "MN", name: "Mongolia", dial: "+976" },
  { iso2: "ME", name: "Montenegro", dial: "+382" },
  { iso2: "MS", name: "Montserrat", dial: "+1664" },
  { iso2: "MA", name: "Morocco", dial: "+212" },
  { iso2: "MZ", name: "Mozambique", dial: "+258" },
  { iso2: "MM", name: "Myanmar", dial: "+95" },
  { iso2: "NA", name: "Namibia", dial: "+264" },
  { iso2: "NR", name: "Nauru", dial: "+674" },
  { iso2: "NP", name: "Nepal", dial: "+977" },
  { iso2: "NL", name: "Netherlands", dial: "+31" },
  { iso2: "NC", name: "New Caledonia", dial: "+687" },
  { iso2: "NZ", name: "New Zealand", dial: "+64" },
  { iso2: "NI", name: "Nicaragua", dial: "+505" },
  { iso2: "NE", name: "Niger", dial: "+227" },
  { iso2: "NG", name: "Nigeria", dial: "+234" },
  { iso2: "NU", name: "Niue", dial: "+683" },
  { iso2: "NF", name: "Norfolk Island", dial: "+672" },
  { iso2: "KP", name: "North Korea", dial: "+850" },
  { iso2: "MK", name: "North Macedonia", dial: "+389" },
  { iso2: "MP", name: "Northern Mariana Islands", dial: "+1670" },
  { iso2: "NO", name: "Norway", dial: "+47" },
  { iso2: "OM", name: "Oman", dial: "+968" },
  { iso2: "PK", name: "Pakistan", dial: "+92" },
  { iso2: "PW", name: "Palau", dial: "+680" },
  { iso2: "PS", name: "Palestine", dial: "+970" },
  { iso2: "PA", name: "Panama", dial: "+507" },
  { iso2: "PG", name: "Papua New Guinea", dial: "+675" },
  { iso2: "PY", name: "Paraguay", dial: "+595" },
  { iso2: "PE", name: "Peru", dial: "+51" },
  { iso2: "PH", name: "Philippines", dial: "+63" },
  { iso2: "PN", name: "Pitcairn Islands", dial: "+64" },
  { iso2: "PL", name: "Poland", dial: "+48" },
  { iso2: "PT", name: "Portugal", dial: "+351" },
  { iso2: "PR", name: "Puerto Rico", dial: "+1787" },
  { iso2: "PR", name: "Puerto Rico", dial: "+1939" },
  { iso2: "QA", name: "Qatar", dial: "+974" },
  { iso2: "RE", name: "Réunion", dial: "+262" },
  { iso2: "RO", name: "Romania", dial: "+40" },
  { iso2: "RU", name: "Russia", dial: "+73" },
  { iso2: "RU", name: "Russia", dial: "+74" },
  { iso2: "RU", name: "Russia", dial: "+75" },
  { iso2: "RU", name: "Russia", dial: "+78" },
  { iso2: "RU", name: "Russia", dial: "+79" },
  { iso2: "RW", name: "Rwanda", dial: "+250" },
  { iso2: "BL", name: "Saint Barthélemy", dial: "+590" },
  { iso2: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", dial: "+290" },
  { iso2: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", dial: "+247" },
  { iso2: "KN", name: "Saint Kitts and Nevis", dial: "+1869" },
  { iso2: "LC", name: "Saint Lucia", dial: "+1758" },
  { iso2: "MF", name: "Saint Martin", dial: "+590" },
  { iso2: "PM", name: "Saint Pierre and Miquelon", dial: "+508" },
  { iso2: "VC", name: "Saint Vincent and the Grenadines", dial: "+1784" },
  { iso2: "WS", name: "Samoa", dial: "+685" },
  { iso2: "SM", name: "San Marino", dial: "+378" },
  { iso2: "ST", name: "São Tomé and Príncipe", dial: "+239" },
  { iso2: "SA", name: "Saudi Arabia", dial: "+966" },
  { iso2: "SN", name: "Senegal", dial: "+221" },
  { iso2: "RS", name: "Serbia", dial: "+381" },
  { iso2: "SC", name: "Seychelles", dial: "+248" },
  { iso2: "SL", name: "Sierra Leone", dial: "+232" },
  { iso2: "SG", name: "Singapore", dial: "+65" },
  { iso2: "SX", name: "Sint Maarten", dial: "+1721" },
  { iso2: "SK", name: "Slovakia", dial: "+421" },
  { iso2: "SI", name: "Slovenia", dial: "+386" },
  { iso2: "SB", name: "Solomon Islands", dial: "+677" },
  { iso2: "SO", name: "Somalia", dial: "+252" },
  { iso2: "ZA", name: "South Africa", dial: "+27" },
  { iso2: "GS", name: "South Georgia", dial: "+500" },
  { iso2: "KR", name: "South Korea", dial: "+82" },
  { iso2: "SS", name: "South Sudan", dial: "+211" },
  { iso2: "ES", name: "Spain", dial: "+34" },
  { iso2: "LK", name: "Sri Lanka", dial: "+94" },
  { iso2: "SD", name: "Sudan", dial: "+249" },
  { iso2: "SR", name: "Suriname", dial: "+597" },
  { iso2: "SJ", name: "Svalbard and Jan Mayen", dial: "+4779" },
  { iso2: "SE", name: "Sweden", dial: "+46" },
  { iso2: "CH", name: "Switzerland", dial: "+41" },
  { iso2: "SY", name: "Syria", dial: "+963" },
  { iso2: "TW", name: "Taiwan", dial: "+886" },
  { iso2: "TJ", name: "Tajikistan", dial: "+992" },
  { iso2: "TZ", name: "Tanzania", dial: "+255" },
  { iso2: "TH", name: "Thailand", dial: "+66" },
  { iso2: "TL", name: "Timor-Leste", dial: "+670" },
  { iso2: "TG", name: "Togo", dial: "+228" },
  { iso2: "TK", name: "Tokelau", dial: "+690" },
  { iso2: "TO", name: "Tonga", dial: "+676" },
  { iso2: "TT", name: "Trinidad and Tobago", dial: "+1868" },
  { iso2: "TN", name: "Tunisia", dial: "+216" },
  { iso2: "TR", name: "Türkiye", dial: "+90" },
  { iso2: "TM", name: "Turkmenistan", dial: "+993" },
  { iso2: "TC", name: "Turks and Caicos Islands", dial: "+1649" },
  { iso2: "TV", name: "Tuvalu", dial: "+688" },
  { iso2: "UG", name: "Uganda", dial: "+256" },
  { iso2: "UA", name: "Ukraine", dial: "+380" },
  { iso2: "AE", name: "United Arab Emirates", dial: "+971" },
  { iso2: "GB", name: "United Kingdom", dial: "+44" },
  { iso2: "US", name: "United States", dial: "+1201" },
  { iso2: "US", name: "United States", dial: "+1202" },
  { iso2: "US", name: "United States", dial: "+1203" },
  { iso2: "US", name: "United States", dial: "+1205" },
  { iso2: "US", name: "United States", dial: "+1206" },
  { iso2: "US", name: "United States", dial: "+1207" },
  { iso2: "US", name: "United States", dial: "+1208" },
  { iso2: "US", name: "United States", dial: "+1209" },
  { iso2: "US", name: "United States", dial: "+1210" },
  { iso2: "US", name: "United States", dial: "+1212" },
  { iso2: "US", name: "United States", dial: "+1213" },
  { iso2: "US", name: "United States", dial: "+1214" },
  { iso2: "US", name: "United States", dial: "+1215" },
  { iso2: "US", name: "United States", dial: "+1216" },
  { iso2: "US", name: "United States", dial: "+1217" },
  { iso2: "US", name: "United States", dial: "+1218" },
  { iso2: "US", name: "United States", dial: "+1219" },
  { iso2: "US", name: "United States", dial: "+1220" },
  { iso2: "US", name: "United States", dial: "+1223" },
  { iso2: "US", name: "United States", dial: "+1224" },
  { iso2: "US", name: "United States", dial: "+1225" },
  { iso2: "US", name: "United States", dial: "+1227" },
  { iso2: "US", name: "United States", dial: "+1228" },
  { iso2: "US", name: "United States", dial: "+1229" },
  { iso2: "US", name: "United States", dial: "+1231" },
  { iso2: "US", name: "United States", dial: "+1234" },
  { iso2: "US", name: "United States", dial: "+1239" },
  { iso2: "US", name: "United States", dial: "+1240" },
  { iso2: "US", name: "United States", dial: "+1248" },
  { iso2: "US", name: "United States", dial: "+1251" },
  { iso2: "US", name: "United States", dial: "+1252" },
  { iso2: "US", name: "United States", dial: "+1253" },
  { iso2: "US", name: "United States", dial: "+1254" },
  { iso2: "US", name: "United States", dial: "+1256" },
  { iso2: "US", name: "United States", dial: "+1260" },
  { iso2: "US", name: "United States", dial: "+1262" },
  { iso2: "US", name: "United States", dial: "+1267" },
  { iso2: "US", name: "United States", dial: "+1269" },
  { iso2: "US", name: "United States", dial: "+1270" },
  { iso2: "US", name: "United States", dial: "+1272" },
  { iso2: "US", name: "United States", dial: "+1274" },
  { iso2: "US", name: "United States", dial: "+1276" },
  { iso2: "US", name: "United States", dial: "+1279" },
  { iso2: "US", name: "United States", dial: "+1281" },
  { iso2: "US", name: "United States", dial: "+1283" },
  { iso2: "US", name: "United States", dial: "+1301" },
  { iso2: "US", name: "United States", dial: "+1302" },
  { iso2: "US", name: "United States", dial: "+1303" },
  { iso2: "US", name: "United States", dial: "+1304" },
  { iso2: "US", name: "United States", dial: "+1305" },
  { iso2: "US", name: "United States", dial: "+1307" },
  { iso2: "US", name: "United States", dial: "+1308" },
  { iso2: "US", name: "United States", dial: "+1309" },
  { iso2: "US", name: "United States", dial: "+1310" },
  { iso2: "US", name: "United States", dial: "+1312" },
  { iso2: "US", name: "United States", dial: "+1313" },
  { iso2: "US", name: "United States", dial: "+1314" },
  { iso2: "US", name: "United States", dial: "+1315" },
  { iso2: "US", name: "United States", dial: "+1316" },
  { iso2: "US", name: "United States", dial: "+1317" },
  { iso2: "US", name: "United States", dial: "+1318" },
  { iso2: "US", name: "United States", dial: "+1319" },
  { iso2: "US", name: "United States", dial: "+1320" },
  { iso2: "US", name: "United States", dial: "+1321" },
  { iso2: "US", name: "United States", dial: "+1323" },
  { iso2: "US", name: "United States", dial: "+1325" },
  { iso2: "US", name: "United States", dial: "+1326" },
  { iso2: "US", name: "United States", dial: "+1327" },
  { iso2: "US", name: "United States", dial: "+1330" },
  { iso2: "US", name: "United States", dial: "+1331" },
  { iso2: "US", name: "United States", dial: "+1332" },
  { iso2: "US", name: "United States", dial: "+1334" },
  { iso2: "US", name: "United States", dial: "+1336" },
  { iso2: "US", name: "United States", dial: "+1337" },
  { iso2: "US", name: "United States", dial: "+1339" },
  { iso2: "US", name: "United States", dial: "+1341" },
  { iso2: "US", name: "United States", dial: "+1346" },
  { iso2: "US", name: "United States", dial: "+1347" },
  { iso2: "US", name: "United States", dial: "+1351" },
  { iso2: "US", name: "United States", dial: "+1352" },
  { iso2: "US", name: "United States", dial: "+1360" },
  { iso2: "US", name: "United States", dial: "+1361" },
  { iso2: "US", name: "United States", dial: "+1364" },
  { iso2: "US", name: "United States", dial: "+1380" },
  { iso2: "US", name: "United States", dial: "+1385" },
  { iso2: "US", name: "United States", dial: "+1386" },
  { iso2: "US", name: "United States", dial: "+1401" },
  { iso2: "US", name: "United States", dial: "+1402" },
  { iso2: "US", name: "United States", dial: "+1404" },
  { iso2: "US", name: "United States", dial: "+1405" },
  { iso2: "US", name: "United States", dial: "+1406" },
  { iso2: "US", name: "United States", dial: "+1407" },
  { iso2: "US", name: "United States", dial: "+1408" },
  { iso2: "US", name: "United States", dial: "+1409" },
  { iso2: "US", name: "United States", dial: "+1410" },
  { iso2: "US", name: "United States", dial: "+1412" },
  { iso2: "US", name: "United States", dial: "+1413" },
  { iso2: "US", name: "United States", dial: "+1414" },
  { iso2: "US", name: "United States", dial: "+1415" },
  { iso2: "US", name: "United States", dial: "+1417" },
  { iso2: "US", name: "United States", dial: "+1419" },
  { iso2: "US", name: "United States", dial: "+1423" },
  { iso2: "US", name: "United States", dial: "+1424" },
  { iso2: "US", name: "United States", dial: "+1425" },
  { iso2: "US", name: "United States", dial: "+1430" },
  { iso2: "US", name: "United States", dial: "+1432" },
  { iso2: "US", name: "United States", dial: "+1434" },
  { iso2: "US", name: "United States", dial: "+1435" },
  { iso2: "US", name: "United States", dial: "+1440" },
  { iso2: "US", name: "United States", dial: "+1442" },
  { iso2: "US", name: "United States", dial: "+1443" },
  { iso2: "US", name: "United States", dial: "+1445" },
  { iso2: "US", name: "United States", dial: "+1447" },
  { iso2: "US", name: "United States", dial: "+1448" },
  { iso2: "US", name: "United States", dial: "+1458" },
  { iso2: "US", name: "United States", dial: "+1463" },
  { iso2: "US", name: "United States", dial: "+1464" },
  { iso2: "US", name: "United States", dial: "+1469" },
  { iso2: "US", name: "United States", dial: "+1470" },
  { iso2: "US", name: "United States", dial: "+1475" },
  { iso2: "US", name: "United States", dial: "+1478" },
  { iso2: "US", name: "United States", dial: "+1479" },
  { iso2: "US", name: "United States", dial: "+1480" },
  { iso2: "US", name: "United States", dial: "+1484" },
  { iso2: "US", name: "United States", dial: "+1500" },
  { iso2: "US", name: "United States", dial: "+1501" },
  { iso2: "US", name: "United States", dial: "+1502" },
  { iso2: "US", name: "United States", dial: "+1503" },
  { iso2: "US", name: "United States", dial: "+1504" },
  { iso2: "US", name: "United States", dial: "+1505" },
  { iso2: "US", name: "United States", dial: "+1507" },
  { iso2: "US", name: "United States", dial: "+1508" },
  { iso2: "US", name: "United States", dial: "+1509" },
  { iso2: "US", name: "United States", dial: "+1510" },
  { iso2: "US", name: "United States", dial: "+1512" },
  { iso2: "US", name: "United States", dial: "+1513" },
  { iso2: "US", name: "United States", dial: "+1515" },
  { iso2: "US", name: "United States", dial: "+1516" },
  { iso2: "US", name: "United States", dial: "+1517" },
  { iso2: "US", name: "United States", dial: "+1518" },
  { iso2: "US", name: "United States", dial: "+1520" },
  { iso2: "US", name: "United States", dial: "+1521" },
  { iso2: "US", name: "United States", dial: "+1522" },
  { iso2: "US", name: "United States", dial: "+1523" },
  { iso2: "US", name: "United States", dial: "+1524" },
  { iso2: "US", name: "United States", dial: "+1525" },
  { iso2: "US", name: "United States", dial: "+1526" },
  { iso2: "US", name: "United States", dial: "+1527" },
  { iso2: "US", name: "United States", dial: "+1528" },
  { iso2: "US", name: "United States", dial: "+1529" },
  { iso2: "US", name: "United States", dial: "+1530" },
  { iso2: "US", name: "United States", dial: "+1531" },
  { iso2: "US", name: "United States", dial: "+1532" },
  { iso2: "US", name: "United States", dial: "+1533" },
  { iso2: "US", name: "United States", dial: "+1534" },
  { iso2: "US", name: "United States", dial: "+1535" },
  { iso2: "US", name: "United States", dial: "+1538" },
  { iso2: "US", name: "United States", dial: "+1539" },
  { iso2: "US", name: "United States", dial: "+1540" },
  { iso2: "US", name: "United States", dial: "+1541" },
  { iso2: "US", name: "United States", dial: "+1542" },
  { iso2: "US", name: "United States", dial: "+1543" },
  { iso2: "US", name: "United States", dial: "+1544" },
  { iso2: "US", name: "United States", dial: "+1545" },
  { iso2: "US", name: "United States", dial: "+1546" },
  { iso2: "US", name: "United States", dial: "+1547" },
  { iso2: "US", name: "United States", dial: "+1549" },
  { iso2: "US", name: "United States", dial: "+1550" },
  { iso2: "US", name: "United States", dial: "+1551" },
  { iso2: "US", name: "United States", dial: "+1552" },
  { iso2: "US", name: "United States", dial: "+1553" },
  { iso2: "US", name: "United States", dial: "+1554" },
  { iso2: "US", name: "United States", dial: "+1556" },
  { iso2: "US", name: "United States", dial: "+1557" },
  { iso2: "US", name: "United States", dial: "+1558" },
  { iso2: "US", name: "United States", dial: "+1559" },
  { iso2: "US", name: "United States", dial: "+1561" },
  { iso2: "US", name: "United States", dial: "+1562" },
  { iso2: "US", name: "United States", dial: "+1563" },
  { iso2: "US", name: "United States", dial: "+1564" },
  { iso2: "US", name: "United States", dial: "+1566" },
  { iso2: "US", name: "United States", dial: "+1567" },
  { iso2: "US", name: "United States", dial: "+1569" },
  { iso2: "US", name: "United States", dial: "+1570" },
  { iso2: "US", name: "United States", dial: "+1571" },
  { iso2: "US", name: "United States", dial: "+1572" },
  { iso2: "US", name: "United States", dial: "+1573" },
  { iso2: "US", name: "United States", dial: "+1574" },
  { iso2: "US", name: "United States", dial: "+1575" },
  { iso2: "US", name: "United States", dial: "+1577" },
  { iso2: "US", name: "United States", dial: "+1578" },
  { iso2: "US", name: "United States", dial: "+1580" },
  { iso2: "US", name: "United States", dial: "+1582" },
  { iso2: "US", name: "United States", dial: "+1585" },
  { iso2: "US", name: "United States", dial: "+1586" },
  { iso2: "US", name: "United States", dial: "+1588" },
  { iso2: "US", name: "United States", dial: "+1589" },
  { iso2: "US", name: "United States", dial: "+1601" },
  { iso2: "US", name: "United States", dial: "+1602" },
  { iso2: "US", name: "United States", dial: "+1603" },
  { iso2: "US", name: "United States", dial: "+1605" },
  { iso2: "US", name: "United States", dial: "+1606" },
  { iso2: "US", name: "United States", dial: "+1607" },
  { iso2: "US", name: "United States", dial: "+1608" },
  { iso2: "US", name: "United States", dial: "+1609" },
  { iso2: "US", name: "United States", dial: "+1610" },
  { iso2: "US", name: "United States", dial: "+1612" },
  { iso2: "US", name: "United States", dial: "+1614" },
  { iso2: "US", name: "United States", dial: "+1615" },
  { iso2: "US", name: "United States", dial: "+1616" },
  { iso2: "US", name: "United States", dial: "+1617" },
  { iso2: "US", name: "United States", dial: "+1618" },
  { iso2: "US", name: "United States", dial: "+1619" },
  { iso2: "US", name: "United States", dial: "+1620" },
  { iso2: "US", name: "United States", dial: "+1623" },
  { iso2: "US", name: "United States", dial: "+1626" },
  { iso2: "US", name: "United States", dial: "+1628" },
  { iso2: "US", name: "United States", dial: "+1629" },
  { iso2: "US", name: "United States", dial: "+1630" },
  { iso2: "US", name: "United States", dial: "+1631" },
  { iso2: "US", name: "United States", dial: "+1636" },
  { iso2: "US", name: "United States", dial: "+1640" },
  { iso2: "US", name: "United States", dial: "+1641" },
  { iso2: "US", name: "United States", dial: "+1646" },
  { iso2: "US", name: "United States", dial: "+1650" },
  { iso2: "US", name: "United States", dial: "+1651" },
  { iso2: "US", name: "United States", dial: "+1656" },
  { iso2: "US", name: "United States", dial: "+1657" },
  { iso2: "US", name: "United States", dial: "+1659" },
  { iso2: "US", name: "United States", dial: "+1660" },
  { iso2: "US", name: "United States", dial: "+1661" },
  { iso2: "US", name: "United States", dial: "+1662" },
  { iso2: "US", name: "United States", dial: "+1667" },
  { iso2: "US", name: "United States", dial: "+1669" },
  { iso2: "US", name: "United States", dial: "+1678" },
  { iso2: "US", name: "United States", dial: "+1679" },
  { iso2: "US", name: "United States", dial: "+1680" },
  { iso2: "US", name: "United States", dial: "+1681" },
  { iso2: "US", name: "United States", dial: "+1682" },
  { iso2: "US", name: "United States", dial: "+1689" },
  { iso2: "US", name: "United States", dial: "+1700" },
  { iso2: "US", name: "United States", dial: "+1701" },
  { iso2: "US", name: "United States", dial: "+1702" },
  { iso2: "US", name: "United States", dial: "+1703" },
  { iso2: "US", name: "United States", dial: "+1704" },
  { iso2: "US", name: "United States", dial: "+1706" },
  { iso2: "US", name: "United States", dial: "+1707" },
  { iso2: "US", name: "United States", dial: "+1708" },
  { iso2: "US", name: "United States", dial: "+1710" },
  { iso2: "US", name: "United States", dial: "+1712" },
  { iso2: "US", name: "United States", dial: "+1713" },
  { iso2: "US", name: "United States", dial: "+1714" },
  { iso2: "US", name: "United States", dial: "+1715" },
  { iso2: "US", name: "United States", dial: "+1716" },
  { iso2: "US", name: "United States", dial: "+1717" },
  { iso2: "US", name: "United States", dial: "+1718" },
  { iso2: "US", name: "United States", dial: "+1719" },
  { iso2: "US", name: "United States", dial: "+1720" },
  { iso2: "US", name: "United States", dial: "+1724" },
  { iso2: "US", name: "United States", dial: "+1725" },
  { iso2: "US", name: "United States", dial: "+1726" },
  { iso2: "US", name: "United States", dial: "+1727" },
  { iso2: "US", name: "United States", dial: "+1730" },
  { iso2: "US", name: "United States", dial: "+1731" },
  { iso2: "US", name: "United States", dial: "+1732" },
  { iso2: "US", name: "United States", dial: "+1734" },
  { iso2: "US", name: "United States", dial: "+1737" },
  { iso2: "US", name: "United States", dial: "+1740" },
  { iso2: "US", name: "United States", dial: "+1743" },
  { iso2: "US", name: "United States", dial: "+1747" },
  { iso2: "US", name: "United States", dial: "+1754" },
  { iso2: "US", name: "United States", dial: "+1757" },
  { iso2: "US", name: "United States", dial: "+1760" },
  { iso2: "US", name: "United States", dial: "+1762" },
  { iso2: "US", name: "United States", dial: "+1763" },
  { iso2: "US", name: "United States", dial: "+1765" },
  { iso2: "US", name: "United States", dial: "+1769" },
  { iso2: "US", name: "United States", dial: "+1770" },
  { iso2: "US", name: "United States", dial: "+1771" },
  { iso2: "US", name: "United States", dial: "+1772" },
  { iso2: "US", name: "United States", dial: "+1773" },
  { iso2: "US", name: "United States", dial: "+1774" },
  { iso2: "US", name: "United States", dial: "+1775" },
  { iso2: "US", name: "United States", dial: "+1779" },
  { iso2: "US", name: "United States", dial: "+1781" },
  { iso2: "US", name: "United States", dial: "+1785" },
  { iso2: "US", name: "United States", dial: "+1786" },
  { iso2: "US", name: "United States", dial: "+1801" },
  { iso2: "US", name: "United States", dial: "+1802" },
  { iso2: "US", name: "United States", dial: "+1803" },
  { iso2: "US", name: "United States", dial: "+1804" },
  { iso2: "US", name: "United States", dial: "+1805" },
  { iso2: "US", name: "United States", dial: "+1806" },
  { iso2: "US", name: "United States", dial: "+1808" },
  { iso2: "US", name: "United States", dial: "+1810" },
  { iso2: "US", name: "United States", dial: "+1812" },
  { iso2: "US", name: "United States", dial: "+1813" },
  { iso2: "US", name: "United States", dial: "+1814" },
  { iso2: "US", name: "United States", dial: "+1815" },
  { iso2: "US", name: "United States", dial: "+1816" },
  { iso2: "US", name: "United States", dial: "+1817" },
  { iso2: "US", name: "United States", dial: "+1818" },
  { iso2: "US", name: "United States", dial: "+1820" },
  { iso2: "US", name: "United States", dial: "+1826" },
  { iso2: "US", name: "United States", dial: "+1828" },
  { iso2: "US", name: "United States", dial: "+1830" },
  { iso2: "US", name: "United States", dial: "+1831" },
  { iso2: "US", name: "United States", dial: "+1832" },
  { iso2: "US", name: "United States", dial: "+1838" },
  { iso2: "US", name: "United States", dial: "+1839" },
  { iso2: "US", name: "United States", dial: "+1840" },
  { iso2: "US", name: "United States", dial: "+1843" },
  { iso2: "US", name: "United States", dial: "+1845" },
  { iso2: "US", name: "United States", dial: "+1847" },
  { iso2: "US", name: "United States", dial: "+1848" },
  { iso2: "US", name: "United States", dial: "+1850" },
  { iso2: "US", name: "United States", dial: "+1854" },
  { iso2: "US", name: "United States", dial: "+1856" },
  { iso2: "US", name: "United States", dial: "+1857" },
  { iso2: "US", name: "United States", dial: "+1858" },
  { iso2: "US", name: "United States", dial: "+1859" },
  { iso2: "US", name: "United States", dial: "+1860" },
  { iso2: "US", name: "United States", dial: "+1862" },
  { iso2: "US", name: "United States", dial: "+1863" },
  { iso2: "US", name: "United States", dial: "+1864" },
  { iso2: "US", name: "United States", dial: "+1865" },
  { iso2: "US", name: "United States", dial: "+1870" },
  { iso2: "US", name: "United States", dial: "+1872" },
  { iso2: "US", name: "United States", dial: "+1878" },
  { iso2: "US", name: "United States", dial: "+1901" },
  { iso2: "US", name: "United States", dial: "+1903" },
  { iso2: "US", name: "United States", dial: "+1904" },
  { iso2: "US", name: "United States", dial: "+1906" },
  { iso2: "US", name: "United States", dial: "+1907" },
  { iso2: "US", name: "United States", dial: "+1908" },
  { iso2: "US", name: "United States", dial: "+1909" },
  { iso2: "US", name: "United States", dial: "+1910" },
  { iso2: "US", name: "United States", dial: "+1912" },
  { iso2: "US", name: "United States", dial: "+1913" },
  { iso2: "US", name: "United States", dial: "+1914" },
  { iso2: "US", name: "United States", dial: "+1915" },
  { iso2: "US", name: "United States", dial: "+1916" },
  { iso2: "US", name: "United States", dial: "+1917" },
  { iso2: "US", name: "United States", dial: "+1918" },
  { iso2: "US", name: "United States", dial: "+1919" },
  { iso2: "US", name: "United States", dial: "+1920" },
  { iso2: "US", name: "United States", dial: "+1925" },
  { iso2: "US", name: "United States", dial: "+1928" },
  { iso2: "US", name: "United States", dial: "+1929" },
  { iso2: "US", name: "United States", dial: "+1930" },
  { iso2: "US", name: "United States", dial: "+1931" },
  { iso2: "US", name: "United States", dial: "+1934" },
  { iso2: "US", name: "United States", dial: "+1936" },
  { iso2: "US", name: "United States", dial: "+1937" },
  { iso2: "US", name: "United States", dial: "+1938" },
  { iso2: "US", name: "United States", dial: "+1940" },
  { iso2: "US", name: "United States", dial: "+1941" },
  { iso2: "US", name: "United States", dial: "+1943" },
  { iso2: "US", name: "United States", dial: "+1945" },
  { iso2: "US", name: "United States", dial: "+1947" },
  { iso2: "US", name: "United States", dial: "+1948" },
  { iso2: "US", name: "United States", dial: "+1949" },
  { iso2: "US", name: "United States", dial: "+1951" },
  { iso2: "US", name: "United States", dial: "+1952" },
  { iso2: "US", name: "United States", dial: "+1954" },
  { iso2: "US", name: "United States", dial: "+1956" },
  { iso2: "US", name: "United States", dial: "+1959" },
  { iso2: "US", name: "United States", dial: "+1970" },
  { iso2: "US", name: "United States", dial: "+1971" },
  { iso2: "US", name: "United States", dial: "+1972" },
  { iso2: "US", name: "United States", dial: "+1973" },
  { iso2: "US", name: "United States", dial: "+1975" },
  { iso2: "US", name: "United States", dial: "+1978" },
  { iso2: "US", name: "United States", dial: "+1979" },
  { iso2: "US", name: "United States", dial: "+1980" },
  { iso2: "US", name: "United States", dial: "+1983" },
  { iso2: "US", name: "United States", dial: "+1984" },
  { iso2: "US", name: "United States", dial: "+1985" },
  { iso2: "US", name: "United States", dial: "+1986" },
  { iso2: "US", name: "United States", dial: "+1989" },
  { iso2: "UM", name: "United States Minor Outlying Islands", dial: "+268" },
  { iso2: "VI", name: "United States Virgin Islands", dial: "+1340" },
  { iso2: "UY", name: "Uruguay", dial: "+598" },
  { iso2: "UZ", name: "Uzbekistan", dial: "+998" },
  { iso2: "VU", name: "Vanuatu", dial: "+678" },
  { iso2: "VA", name: "Vatican City", dial: "+3906698" },
  { iso2: "VA", name: "Vatican City", dial: "+379" },
  { iso2: "VE", name: "Venezuela", dial: "+58" },
  { iso2: "VN", name: "Vietnam", dial: "+84" },
  { iso2: "WF", name: "Wallis and Futuna", dial: "+681" },
  { iso2: "EH", name: "Western Sahara", dial: "+2125288" },
  { iso2: "EH", name: "Western Sahara", dial: "+2125289" },
  { iso2: "YE", name: "Yemen", dial: "+967" },
  { iso2: "ZM", name: "Zambia", dial: "+260" },
  { iso2: "ZW", name: "Zimbabwe", dial: "+263" },
];

const dialByIso = new Map<string, string>();
for (const e of COUNTRY_DIAL_ENTRIES) {
  if (!dialByIso.has(e.iso2)) dialByIso.set(e.iso2, e.dial);
}

/** Primary (first-listed) dial code for an ISO2 country. */
export function getDialCodeForIso(iso2: string): string {
  const up = iso2.trim().toUpperCase();
  return dialByIso.get(up) ?? "+92";
}

/** Default `value` for country+code selects (`ISO|E.164dial`). */
export const DEFAULT_PHONE_COUNTRY_KEY = "PK|+92";

/** Dial part from a select key `ISO|+digits` (or a bare `+digits` string). */
export function dialFromPhoneCountryKey(key: string): string {
  const k = (key || "").trim();
  const pipe = k.indexOf("|");
  if (pipe === -1) return k.startsWith("+") ? k : "+92";
  const dial = k.slice(pipe + 1).trim();
  return dial.startsWith("+") ? dial : `+${dial}`;
}

/** Longest-prefix match of E.164 dial against known codes (sorted by dial length desc). */
const SORTED_DIAL_PREFIXES: { dial: string; iso2: string }[] = (() => {
  const seenDial = new Set<string>();
  const list: { dial: string; iso2: string }[] = [];
  for (const e of COUNTRY_DIAL_ENTRIES) {
    if (seenDial.has(e.dial)) continue;
    seenDial.add(e.dial);
    list.push({ dial: e.dial, iso2: e.iso2 });
  }
  list.sort((a, b) => b.dial.length - a.dial.length);
  return list;
})();

function digitsOnly(s: string): string {
  return s.replace(/\D/g, "");
}

/**
 * Split a stored phone string into select key + national digits for UI.
 * Falls back to PK|+92 and full digit string as national if no dial matches.
 */
export function parsePhoneForDisplay(stored: string): { phoneCountryKey: string; national: string } {
  const raw = (stored || "").trim();
  if (!raw) return { phoneCountryKey: DEFAULT_PHONE_COUNTRY_KEY, national: "" };
  let rest = raw.startsWith("+") ? raw.slice(1) : raw;
  rest = digitsOnly(rest);
  if (!rest) return { phoneCountryKey: DEFAULT_PHONE_COUNTRY_KEY, national: "" };
  for (const { dial, iso2 } of SORTED_DIAL_PREFIXES) {
    const d = dial.slice(1);
    if (rest.startsWith(d)) {
      return { phoneCountryKey: `${iso2}|${dial}`, national: rest.slice(d.length) };
    }
  }
  return { phoneCountryKey: DEFAULT_PHONE_COUNTRY_KEY, national: rest };
}

/** E.164-style full number from select key + national digits. */
export function composeInternationalPhone(phoneCountryKey: string, nationalDigits: string): string {
  const dial = dialFromPhoneCountryKey(phoneCountryKey);
  const n = digitsOnly(nationalDigits);
  return n ? `${dial}${n}` : "";
}