/**
 * Common HEC (Higher Education Commission of Pakistan) recognized degree
 * programs offered across Pakistani universities. Used to power the
 * searchable "Program" dropdown on student signup.
 *
 * Keep in sync with ciel_backend/src/auth/constants/hec-programs.ts
 */
export const hecPrograms = [
    "Associate Degree in Business Administration",
    "Associate Degree in Computer Science",
    "BA (Bachelor of Arts)",
    "BA LLB (Hons)",
    "BBA (Bachelor of Business Administration)",
    "BDS (Bachelor of Dental Surgery)",
    "BS Accounting and Finance",
    "BS Actuarial Sciences",
    "BS Agricultural Sciences",
    "BS Agriculture",
    "BS Animation",
    "BS Anthropology",
    "BS Applied Psychology",
    "BS Architecture",
    "BS Artificial Intelligence",
    "BS Biochemistry",
    "BS Biology",
    "BS Biomedical Engineering",
    "BS Biotechnology",
    "BS Botany",
    "BS Business Analytics",
    "BS Chemical Engineering",
    "BS Chemistry",
    "BS Civil Engineering",
    "BS Commerce",
    "BS Computer Engineering",
    "BS Computer Science",
    "BS Criminology",
    "BS Cyber Security",
    "BS Data Science",
    "BS Early Childhood Education",
    "BS Economics",
    "BS Education",
    "BS Electrical Engineering",
    "BS Electronic Engineering",
    "BS English Language and Literature",
    "BS English Linguistics",
    "BS Environmental Sciences",
    "BS Fashion Design",
    "BS Fine Arts",
    "BS Food Science and Technology",
    "BS Forestry",
    "BS Geography",
    "BS Geology",
    "BS Graphic Design",
    "BS History",
    "BS Home Economics",
    "BS Hospitality and Tourism Management",
    "BS Human Resource Management",
    "BS Industrial Engineering",
    "BS Information Technology",
    "BS Interior Design",
    "BS International Relations",
    "BS Islamic Studies",
    "BS Journalism",
    "BS Law",
    "BS Library and Information Sciences",
    "BS Marketing",
    "BS Mass Communication",
    "BS Mathematics",
    "BS Mechanical Engineering",
    "BS Mechatronics Engineering",
    "BS Media Studies",
    "BS Medical Laboratory Technology",
    "BS Metallurgical and Materials Engineering",
    "BS Microbiology",
    "BS Mining Engineering",
    "BS Multimedia Arts",
    "BS Music",
    "BS Nursing",
    "BS Nutrition and Dietetics",
    "BS Petroleum Engineering",
    "BS Pharmacy",
    "BS Physical Education",
    "BS Physics",
    "BS Physiotherapy",
    "BS Political Science",
    "BS Project Management",
    "BS Psychology",
    "BS Public Administration",
    "BS Radiology and Imaging Technology",
    "BS Social Work",
    "BS Sociology",
    "BS Software Engineering",
    "BS Sports Sciences",
    "BS Statistics",
    "BS Supply Chain Management",
    "BS Textile Design",
    "BS Textile Engineering",
    "BS Urban and Regional Planning",
    "BS Urdu",
    "BS Veterinary Sciences",
    "BS Visual Arts",
    "BS Zoology",
    "B.Com (Bachelor of Commerce)",
    "B.Ed (Bachelor of Education)",
    "DPT (Doctor of Physical Therapy)",
    "DVM (Doctor of Veterinary Medicine)",
    "LLB (Bachelor of Laws)",
    "LLM (Master of Laws)",
    "M.Ed (Master of Education)",
    "MA (Master of Arts)",
    "MBA (Master of Business Administration)",
    "MBBS (Bachelor of Medicine, Bachelor of Surgery)",
    "MPhil Business Administration",
    "MPhil Chemistry",
    "MPhil Computer Science",
    "MPhil Economics",
    "MPhil Education",
    "MPhil English",
    "MPhil Islamic Studies",
    "MPhil Mathematics",
    "MPhil Physics",
    "MPhil Public Administration",
    "MPhil Sociology",
    "MS Aerospace Engineering",
    "MS Artificial Intelligence",
    "MS Biotechnology",
    "MS Computer Science",
    "MS Data Science",
    "MS Electrical Engineering",
    "MS Environmental Sciences",
    "MS Management Sciences",
    "MS Mathematics",
    "MS Project Management",
    "MS Software Engineering",
    "MS Statistics",
    "Pharm-D (Doctor of Pharmacy)",
    "PhD Biological Sciences",
    "PhD Business Administration",
    "PhD Chemistry",
    "PhD Computer Science",
    "PhD Economics",
    "PhD Education",
    "PhD Engineering",
    "PhD English",
    "PhD Islamic Studies",
    "PhD Mathematics",
    "PhD Physics",
    "PhD Social Sciences",
].sort();
