/**
 * Canonical Pakistan regions for profile & opportunity city dropdowns.
 * Keep spellings in sync with `ciel_backend/src/admin/admin.service.ts` (`STAKEHOLDER_REGION_CANONICAL`).
 */
export const PAKISTAN_REGION_OPTIONS = [
    'Abbottabad',
    'Attock',
    'Azad Jammu and Kashmir',
    'Bahawalnagar',
    'Bahawalpur',
    'Balochistan',
    'Charsadda',
    'Chiniot',
    'Dera Ghazi Khan',
    'Dera Ismail Khan',
    'Faisalabad',
    'Gilgit',
    'Gilgit-Baltistan',
    'Gujranwala',
    'Gujrat',
    'Haripur',
    'Hyderabad',
    'Islamabad',
    'Islamabad Capital Territory',
    'Jhang',
    'Kamoke',
    'Karachi',
    'Kasur',
    'Khyber Pakhtunkhwa',
    'Kohat',
    'Lahore',
    'Larkana',
    'Mandi Bahauddin',
    'Mansehra',
    'Mardan',
    'Mingora',
    'Mirpur Khas',
    'Multan',
    'Murree',
    'Nawabshah',
    'Okara',
    'Peshawar',
    'Punjab',
    'Quetta',
    'Rahim Yar Khan',
    'Rawalpindi',
    'Sahiwal',
    'Sargodha',
    'Sheikhupura',
    'Sialkot',
    'Skardu',
    'Sindh',
    'Sukkur',
    'Swabi',
    'Taxila',
    'Wah Cantonment',
] as const;

/** Provinces / federal territories — for organisation “Region / Province” fields. */
export const PAKISTAN_PROVINCE_OPTIONS = [
    'Azad Jammu and Kashmir',
    'Balochistan',
    'Gilgit-Baltistan',
    'Islamabad Capital Territory',
    'Khyber Pakhtunkhwa',
    'Punjab',
    'Sindh',
] as const;
