export const pakistaniUniversities = [
    "Aga Khan University",
    "Air University",
    "Allama Iqbal Open University",
    "Bahria University",
    "Bahauddin Zakariya University",
    "Balochistan University of Information Technology, Engineering and Management Sciences (BUITEMS)",
    "COMSATS University Islamabad",
    "Dawood University of Engineering and Technology",
    "Dow University of Health Sciences",
    "Fatima Jinnah Women University",
    "Federal Urdu University of Arts, Science and Technology",
    "Ghanshyam Das Birla Institute of Technology (BIT)",
    "Ghulam Ishaq Khan Institute of Engineering Sciences and Technology (GIKI)",
    "Government College University, Lahore",
    "Government College University, Faisalabad",
    "Habib University",
    "Hamdard University",
    "Information Technology University (ITU)",
    "Institute of Business Administration (IBA)",
    "Institute of Business Management (IoBM)",
    "Institute of Management Sciences (IMSciences)",
    "Institute of Space Technology (IST)",
    "International Islamic University, Islamabad",
    "Iqra University",
    "Islamia College University",
    "Jinnah Sindh Medical University",
    "Karakoram International University",
    "Karachi School of Business and Leadership (KSBL)",
    "Kinnaird College for Women",
    "Kohat University of Science and Technology",
    "Lahore School of Economics (LSE)",
    "Lahore University of Management Sciences (LUMS)",
    "Lasbela University of Agriculture, Water and Marine Sciences",
    "Liaquat University of Medical and Health Sciences",
    "Mehran University of Engineering and Technology",
    "National College of Arts (NCA)",
    "National Defence University",
    "National University of Computer and Emerging Sciences (FAST-NUCES)",
    "National University of Modern Languages (NUML)",
    "National University of Sciences and Technology (NUST)",
    "National University of Technology (NUTECH)",
    "NED University of Engineering and Technology",
    "Pakistan Institute of Development Economics (PIDE)",
    "Pakistan Institute of Engineering and Applied Sciences (PIEAS)",
    "Pakistan Military Academy",
    "Pakistan Naval Academy",
    "Pir Mehr Ali Shah Arid Agriculture University",
    "Punjab University",
    "Quaid-i-Azam University",
    "Sardar Bahadur Khan Women's University",
    "Shah Abdul Latif University",
    "Shaheed Behezir Bhutto Women University",
    "Shaheed Zulfiqar Ali Bhutto Institute of Science and Technology (SZABIST)",
    "Sindh Agriculture University",
    "Sindh Madressatul Islam University",
    "Sir Syed University of Engineering and Technology",
    "Sukkur IBA University",
    "The Islamia University of Bahawalpur",
    "University of Agriculture, Faisalabad",
    "University of Agriculture, Peshawar",
    "University of Balochistan",
    "University of Central Punjab",
    "University of Engineering and Technology, Lahore",
    "University of Engineering and Technology, Peshawar",
    "University of Engineering and Technology, Taxila",
    "University of Gujrat",
    "University of Karachi",
    "University of Management and Technology (UMT)",
    "University of Peshawar",
    "University of Sargodha",
    "University of Sindh",
    "University of Veterinary and Animal Sciences",
    "Virtual University of Pakistan",
    "Ziauddin University"
].sort();
